version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  fastapi:
    build:
      context: ..
      dockerfile: devops/Dockerfile.backend
    container_name: FAST-API
    hostname: fastapi
    volumes:
      - ../storage/tmp:/app/tmp
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - WEBSITE_URL=http://site
      - BACKEND_INPUT_QUEUE=output
      - BACKEND_OUTPUT_QUEUE=input
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - rabbitmq
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:23.08-py3
    command: ["tritonserver", "--model-repository=/models"]
    volumes:
      - ../tensorrt_models_running:/models      # Папка с движками моделей и конфигами
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:                                     # Разрешение на использование GPU
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
  adapter:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: devops/Dockerfile.adapter     
    volumes:
      - ../storage:/adapter_triton/storage      # Монтируемое хранилилище
    privileged: true
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - INPUT_QUEUE=input
      - OUTPUT_QUEUE=output
    deploy:
      replicas: 1

  php-apache-environment:
    container_name: php-apache
    hostname: site
    build:
      context: ..
      dockerfile: ./site/public_html/docker/php-apache/Dockerfile
    volumes:
      - ../site/public_html/src:/var/www/html/
      - ../site/public_html/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - BACKEND_API_URL=http://fastapi
      - SITE_PORT=${SITE_PORT}
    env_file:
      - ./.env
    ports:
      - ${SITE_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT