version: '3'

services:
  vsgan_tensorrt:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: borntowarn/tensorrt:latest
    volumes:
      - ../weights:/workspace/tensorrt
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia