FROM python:3.10

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY ../requirements.txt ./
RUN pip install -r requirements.txt

WORKDIR adapter_triton

COPY ../src src/
COPY adapter.py adapter.py

CMD ["python", "adapter.py"]
